# Generated by Django 2.0 on 2018-03-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='category',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.CharField(default='', max_length=150),
        ),
    ]
