# Generated by Django 2.0 on 2018-01-28 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='categ',
        ),
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='accounts.Category'),
        ),
    ]
