# Generated by Django 2.0 on 2018-01-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180128_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.ManyToManyField(related_name='category', to='accounts.Category'),
        ),
    ]
